[package]
name = "mws-cli"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]
edition = "2018"

[dependencies]
mws = { path = "../mws" }
dotenv = "0.15.0"
structopt = { version = "0.3", default-features = false }
chrono = { version = "0.4" }
encoding_rs = "0.8.22"